
services:
  api:
    build:
      context: .
      dockerfile: DockerfilePython
    ports:
      - "8000:8000"
    environment:
      - MYSQL_DATABASE 
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_HOST=db
      - MYSQL_USER 
    restart: always
    depends_on:
      db: 
        condition: service_healthy
#il faut faire composer build et faire le healthcheck aussi
  db:
    image: mysql:9.2
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      # - MYSQL_DATABASE
      # - MYSQL_USER
      
    ports:
      - "3306:3306"
    healthcheck:
      # test: "mysqladmin ping -h localhost -u root -p MYSQL_ROOT_PASSWORD | exit 1 "
       test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$MYSQL_ROOT_PASSWORD || exit 1"]

    volumes:
      - ./sqlfiles/:/docker-entrypoint-initdb.d
