# Use root/example as user/password credentials


services:
  db: 
    image: mysql-migration
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-defaultpassword}

    volumes:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    
